//! Memory-read and integer-conversion output types.

use rmcp::schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Raw bytes read at one address.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct BytesResult {
    /// Address the read started at, hex-formatted.
    pub address: String,
    /// The bytes, lowercase hex, no separators.
    pub bytes: String,
    /// Number of bytes actually read; may be shorter than requested.
    pub length: usize,
}

/// One address's bytes within a multi-address `get_bytes` call.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct GetBytesBatchEntry {
    /// The address this entry answers for, hex-formatted.
    pub address: String,
    /// The full read result; absent when the read failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bytes: Option<BytesResult>,
    /// Why this address could not be read; absent on success.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// `get_bytes` output.
///
/// One address (or a `target_name`) flattens the read onto the root; several
/// fill `results`, where each entry nests the whole read under `bytes`.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct GetBytesOutput {
    /// Address the read started at, hex-formatted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// The bytes, lowercase hex, no separators.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bytes: Option<String>,
    /// Number of bytes actually read.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub length: Option<usize>,
    /// One entry per address when several were requested.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<GetBytesBatchEntry>>,
}

/// One integer read out of the database.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct IntReadResult {
    /// Address read from, hex-formatted.
    pub address: String,
    /// Width of the read in bytes: 1, 2, 4 or 8.
    pub size: usize,
    /// The value, zero-extended to 64 bits.
    pub value: u64,
    /// The same value, hex-formatted.
    pub hex: String,
}

/// One address's value within a multi-address `get_u8`/`get_u16`/`get_u32`/
/// `get_u64` call.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct IntReadBatchEntry {
    /// The address this entry answers for, hex-formatted.
    pub address: String,
    /// The full read result; absent when the read failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<IntReadResult>,
    /// Why this address could not be read; absent on success.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// One generated byte signature.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct SignatureResult {
    /// The address the pattern starts at, hex-formatted.
    pub address: String,
    /// The rendered pattern, in the requested format.
    pub signature: String,
    /// Which rendering was used.
    pub format: String,
    /// Pattern length in bytes.
    pub length: usize,
    /// How many instructions the pattern covers.
    pub instructions: usize,
    /// True when the pattern matches exactly one place in the database.
    pub unique: bool,
    /// Whether operand bytes were wildcarded.
    pub wildcard_operands: bool,
    /// True when growth stopped at `max_length` without becoming unique.
    pub truncated: bool,
    /// Set instead of a signature when one address of a batch failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// `make_signature` output: one address flattens onto the root, several fill
/// `results`.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct MakeSignatureOutput {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub length: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instructions: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unique: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wildcard_operands: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub truncated: Option<bool>,
    /// One entry per address when several were requested.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<SignatureResult>>,
}

/// One typed integer read, as `get_int` returns it.
///
/// `value` is a decimal string rather than a JSON number because a `u64` past
/// 2^53 and a negative `i64` cannot both survive a JSON number.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct TypedIntRead {
    /// Address read from, hex-formatted.
    pub address: String,
    /// The integer type this was read as, e.g. `i32` or `u16be`.
    pub ty: String,
    /// Width of the read in bytes.
    pub size: usize,
    /// The value as a decimal string; negative when the type is signed.
    pub value: String,
    /// The raw bits, hex-formatted.
    pub hex: String,
    /// The bytes as they sit in memory, before byte-order interpretation.
    pub bytes: String,
    /// Set instead of the read when one address of a batch failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// `get_int` output: one address flattens onto the root, several fill
/// `results`.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct GetTypedIntOutput {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ty: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hex: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bytes: Option<String>,
    /// One entry per address when several were requested.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<TypedIntRead>>,
}

/// `put_int` output: what was written, and the bytes it became.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct PutIntOutput {
    /// Address written to, hex-formatted.
    pub address: String,
    /// The integer type the value was encoded as.
    pub ty: String,
    /// Number of bytes written.
    pub size: usize,
    /// The value as a decimal string.
    pub value: String,
    /// The bytes written, hex-formatted.
    pub bytes: String,
}

/// `get_u8` / `get_u16` / `get_u32` / `get_u64` output.
///
/// One address flattens the read onto the root; several fill `results`, where
/// each entry nests the whole read under `value`.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct GetIntOutput {
    /// Address read from, hex-formatted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Width of the read in bytes.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<usize>,
    /// The value, zero-extended to 64 bits.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<u64>,
    /// The same value, hex-formatted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hex: Option<String>,
    /// One entry per address when several were requested.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<IntReadBatchEntry>>,
}

/// One NUL-terminated string read out of memory.
///
/// Unlike the `strings` tools this reads whatever bytes are at the address; it
/// does not require IDA to have detected a string there.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct StringReadResult {
    /// Address read from, hex-formatted.
    pub address: String,
    /// Decoded text, lossy UTF-8, up to the first NUL.
    pub string: String,
    /// Length in bytes up to the NUL.
    pub length: usize,
    /// The same bytes, lowercase hex, no separators.
    pub bytes: String,
}

/// One address's string within a multi-address `get_string` call.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct GetStringBatchEntry {
    /// The address this entry answers for, hex-formatted.
    pub address: String,
    /// The full read result; absent when the read failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub string: Option<StringReadResult>,
    /// Why this address could not be read; absent on success.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// `get_string` output.
///
/// One address flattens the read onto the root; several fill `results`, where
/// each entry nests the whole read under `string`.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct GetStringOutput {
    /// Address read from, hex-formatted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Decoded text, lossy UTF-8, up to the first NUL.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub string: Option<String>,
    /// Length in bytes up to the NUL.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub length: Option<usize>,
    /// The same bytes, lowercase hex, no separators.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bytes: Option<String>,
    /// One entry per address when several were requested.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<GetStringBatchEntry>>,
}

/// The 8 bytes stored at a global symbol, read as a little-endian integer.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct GlobalValueResult {
    /// Address the symbol resolved to, hex-formatted.
    pub address: String,
    /// The 8 bytes as a little-endian u64.
    pub value: u64,
    /// The same value, hex-formatted.
    pub hex: String,
    /// The raw 8 bytes, lowercase hex, no separators.
    pub bytes: String,
}

/// One query's value within a multi-query `get_global_value` call.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct GlobalValueBatchEntry {
    /// The query exactly as supplied — a symbol name or an address.
    pub query: String,
    /// The full read result; absent when the query failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<GlobalValueResult>,
    /// Why this query could not be answered; absent on success.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// `get_global_value` output.
///
/// One query flattens the read onto the root; several fill `results`, where
/// each entry nests the whole read under `value`.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct GetGlobalValueOutput {
    /// Address the symbol resolved to, hex-formatted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// The 8 bytes as a little-endian u64.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<u64>,
    /// The same value, hex-formatted.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hex: Option<String>,
    /// The raw 8 bytes, lowercase hex, no separators.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bytes: Option<String>,
    /// One entry per query when several were requested.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<GlobalValueBatchEntry>>,
}

/// One converted integer, or the reason the input could not be parsed.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct IntConvertEntry {
    /// The input string exactly as supplied.
    pub input: String,
    /// Parsed value as a JSON number.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<u64>,
    /// Decimal rendering.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dec: Option<String>,
    /// Hexadecimal rendering with a `0x` prefix.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hex: Option<String>,
    /// Binary rendering with a `0b` prefix.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bin: Option<String>,
    /// Little-endian bytes, hex, trailing zero bytes trimmed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bytes_le: Option<String>,
    /// Big-endian bytes, hex, leading zero bytes trimmed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bytes_be: Option<String>,
    /// Little-endian bytes rendered as ASCII, `.` for unprintable bytes.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ascii: Option<String>,
    /// Why the input could not be parsed; absent on success.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// `int_convert` output.
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct IntConvertOutput {
    /// One entry per input, in the order supplied.
    pub results: Vec<IntConvertEntry>,
}
